import { chromium } from '@playwright/test';
const [out, url, name, anchor, w] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: Number(w || 1440), height: 900 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(String(e))); page.on('console', m => { if (m.type()==='error') errs.push(m.text().slice(0,200)); });
const res = await page.goto('http://localhost:4321' + url + (anchor ? '#' + anchor : ''), { waitUntil: 'networkidle', timeout: 90000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/${name}.png` });
console.log(name, res.status(), errs.slice(0,3).join(' | '), 'docW', await page.evaluate(() => document.documentElement.scrollWidth));
await browser.close();
