/** Stable parser examples captured from the original manuscripts.
 * Parser contracts must survive scientific revisions to the live book; the
 * integration tests separately validate every currently authored fence.
 * These are syntax fixtures, not current scientific claims.
 */
export const PARSER_REGRESSIONS = {
  forward:
    'Tensor trace \u2014 reference decoder-only forward pass (pre-norm, learned positions)\n[B, T] int64                 \u2192 gather E[x]            \u2192 [B, T, D]        h_0 (embedding)\n[B, T, D] + [T, D]           \u2192 broadcast add P        \u2192 [B, T, D]        h_0 (positioned)\n--- block \u2113 (repeated L times) ---\n[B, T, D]                    \u2192 RMSNorm(g_att)         \u2192 [B, T, D]        n_att\n[B, T, D] \u00d7 [D, 3D]          \u2192 QKV projection         \u2192 [B, T, 3, H, Dh] qkv (packed)\n[B, T, 3, H, Dh]             \u2192 split + transpose      \u2192 3 \u00d7 [B, H, T, Dh] Q, K, V\n[B, H, T, Dh] \u00d7 [B, H, Dh, T]\u2192 batched matmul / \u221aDh   \u2192 [B, H, T, T]     scores  (\u00a75.2)\n[B, H, T, T] + [T, T]        \u2192 causal mask, softmax   \u2192 [B, H, T, T]     probs   (\u00a75.2)\n[B, H, T, T] \u00d7 [B, H, T, Dh] \u2192 batched matmul         \u2192 [B, H, T, Dh]    ctx\n[B, H, T, Dh]                \u2192 transpose + merge      \u2192 [B, T, D]        ctx (merged)\n[B, T, D] \u00d7 [D, D]           \u2192 output projection W_O  \u2192 [B, T, D]        a\n[B, T, D] + [B, T, D]        \u2192 residual add           \u2192 [B, T, D]        h_mid\n[B, T, D]                    \u2192 RMSNorm(g_ffn)         \u2192 [B, T, D]        n_ffn\n[B, T, D] \u00d7 [D, F]           \u2192 W_1                    \u2192 [B, T, F]        u       (\u00a75.3)\n[B, T, F]                    \u2192 GELU (or gated act)    \u2192 [B, T, F]        v\n[B, T, F] \u00d7 [F, D]           \u2192 W_2                    \u2192 [B, T, D]        f\n[B, T, D] + [B, T, D]        \u2192 residual add           \u2192 [B, T, D]        h_\u2113\n--- end block ---\n[B, T, D]                    \u2192 RMSNorm(g_L)           \u2192 [B, T, D]        n_L\n[B, T, D] \u00d7 [D, V]           \u2192 output head W_out      \u2192 [B, T, V]        logits z\n[B, T, V], [B, T] int64      \u2192 log-softmax + gather   \u2192 scalar           loss (\u00a75.5)',
  cost: 'Tensor trace\n[B, T, D] \u2192 linear W_qkv [D, 3\u00b7H\u00b7Dh] \u2192 [B, T, 3\u00b7H\u00b7Dh] \u2192 view \u2192 [B, T, 3, H, Dh] \u2192 permute \u2192 3 \u00d7 [B, H, T, Dh]\n[B, H, T, Dh] \u00d7 [B, H, Dh, T] \u2192 batched matmul \u2192 [B, H, T, T]      # 2\u00b7B\u00b7H\u00b7T\u00b2\u00b7Dh FLOPs, output B\u00b7H\u00b7T\u00b2\u00b7b bytes\n[B, H, T, T] \u00d7 [B, H, T, Dh] \u2192 batched matmul \u2192 [B, H, T, Dh]      # 2\u00b7B\u00b7H\u00b7T\u00b2\u00b7Dh FLOPs',
  mtp: 'Tensor trace (D = 1 MTP)\n[B, T, d] h^0 \u2500\u252c\u2192 OutHead \u2192 [B, T, V] \u2192 CE \u2192 L_NTP\n               \u2514\u2192 slice [B, T\u22121, d] \u2295 Emb(x_{t+1}) [B, T\u22121, d] \u2192 concat [B, T\u22121, 2d] \u2192 M_1 \u2192 [B, T\u22121, d] \u2192 TRM_1 \u2192 [B, T\u22121, d] \u2192 OutHead \u2192 [B, T\u22121, V] \u2192 CE \u2192 L_MTP',
  span: 'Tensor trace (encoder\u2013decoder span corruption)\n[B, T\u0303] x\u0303 \u2192 encoder (bidirectional) \u2192 [B, T\u0303, D] enc\n[B, |y|] y_shifted \u2192 decoder self-attn (causal) + cross-attn over enc \u2192 [B, |y|, D] \u2192 W_out \u2192 [B, |y|, V] \u2192 CE over all |y| positions',
  mixed:
    'Systems trace (single device, one Linear layer, BF16-operand recipe)\nstage                 \u2192 latency          / memory                           / compute        / communication / failure\ncast master\u2192operand   \u2192 1 pass over W    / +2 B/param operand copy          / elementwise    / none          / none\nGEMM forward          \u2192 tensor-core bound/ activations saved in BF16        / 2\u00b7M\u00b7N\u00b7K FLOPs  / none          / overflow if FP16\nGEMM backward (2\u00d7)    \u2192 tensor-core bound/ grads in BF16 then FP32          / 4\u00b7M\u00b7N\u00b7K FLOPs  / none          / underflow if FP16, no S\nunscale + clip        \u2192 2 passes over g  / FP32 gradient buffer 4 B/param   / elementwise    / none          / NaN norm\noptimizer step        \u2192 1 pass over \u03b8_32 / master 4 B + m 4 B + v 4 B       / elementwise    / none          / lost update if BF16 master',
  repro:
    'Systems trace (one training step, sources of non-identity)\nstage            \u2192 latency effect        / memory            / compute / communication / failure (non-identity source)\ndata loading     \u2192 none                  / none              / none    / none          / worker RNG order\nembedding bwd    \u2192 atomics fast          / none              / same    / none          / atomic scatter order\nGEMMs            \u2192 split-K faster        / +24 MiB if pinned / same    / none          / split-K / multi-stream order\nattention kernel \u2192 engine-dependent      / engine-dependent  / same    / none          / cuDNN engine selection\nsoftmax / norms  \u2192 deterministic         / none              / same    / none          / none (fixed order)\nclip + optimizer \u2192 deterministic         / none              / same    / none          / none on one device',
  acquisition:
    'Systems trace (per-source acquisition)\nacquire \u2192 latency: network-bound / memory: streaming / compute: negligible / communication: egress from custodian / failure: partial manifests, moved URIs\nstore raw \u2192 latency: n/a / memory: Z bytes \u00d7 retention time / compute: none / communication: replication / failure: raw deleted before lineage audit\nextract \u2192 latency: CPU-bound / memory: per-document / compute: h_ext core-hours / communication: shard I/O / failure: silent content loss (\u00a77.3)\ncount tokens \u2192 latency: one tokenizer pass / memory: streaming / compute: O(bytes) / communication: none / failure: tokenizer not recorded',
  controlled:
    'Systems trace (one factorial cell)\ncurate data     \u2192 compute: C_curate (classifier or dedup pass over the pool) / storage: filtered shard set / failure: unlogged compute\ntrain           \u2192 compute: 6\u00b7N\u00b7D FLOPs / memory, communication: per Chapters 29\u201330 / failure: divergent run replaced by a re-run (must be recorded)\nevaluate        \u2192 compute: \u22482N FLOPs \u00d7 evaluated tokens \u00d7 tasks / failure: arm-specific prompt or few-shot seed\nrecord          \u2192 storage: run config + consumed-token log + per-sample outcomes / failure: aggregates only',
  rights:
    'Systems trace (removal request \u2192 remediation)\nresolve seed \u2192 latency: index lookup / memory: O(seed) / failure: URL-only scope cannot resolve archived copies\nclosure (Eq. 7.9) \u2192 latency: O(|V|+|E|) / memory: visited set, disk-backed frontier / failure: missing use edges \u2192 silent under-closure\nact per class \u2192 raw, shard, cache, index, backup: delete or tombstone / model: review task / failure: one inaccessible backup marked complete\npublish view \u2192 latency: manifest write / communication: invalidation to workers / failure: worker cache without release id',
  frontier:
    'Systems trace\nimmutable workload -> replay scheduled arrivals / bounded queue / record rejected requests\nengine             -> token generation / checkpoint + KV bytes / collect runtime identity\nclient             -> monotonic delivery timestamps / preserve timeout and cancellation events\nscorer             -> independent correctness decision / retain output and scorer hashes\njoin               -> request-id keyed quality + service record / reject missing pairs\nanalysis           -> constraints then frontier / retain raw points and uncertainty',
  concept:
    'flowchart TD\n    A["[Tensor] token ids [B, T]"] --> B["[Process] embedding gather"]\n    B --> C["[Tensor] residual stream [B, T, D]"]\n    P["[Tensor] position table [T, D]"] --> C\n    C --> N1["[Process] RMSNorm"]\n    N1 --> Q["[Tensor] Q, K, V [B, H, T, Dh]"]\n    Q --> S["[Tensor] scores [B, H, T, T]"]\n    S --> M["[Process] causal mask + softmax"]\n    M --> O["[Tensor] attention output [B, T, D]"]\n    O --> C\n    C --> N2["[Process] RMSNorm"]\n    N2 --> F["[Tensor] FFN hidden [B, T, F]"]\n    F --> C\n    C --> H["[Process] final norm + output head"]\n    H --> L["[Tensor] logits [B, T, V]"]\n    L --> J["[Objective] shifted-target cross-entropy"]\n    K["[Memory] KV cache [L, B, S, Hkv, Dh]"] -. "decode reuse" .-> Q\n    S -. "O(T\u00b2) bytes" .-> MEM["[Memory] activation memory"]\n    F -. "O(T\u00b7F) bytes" .-> MEM',
} as const;
